spring.application.name=TDTVSystem

spring.datasource.url=jdbc:mysql://localhost:3307/TDTVSystem
spring.datasource.username=root
spring.datasource.password=tdtvsystem
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.privateKey=qbIgCPwRuv6GanDkpZ3DwfIYVOPrYkdHX7/56jB9JBo=
jwt.expiration=86400000

spring.security.user.name=TDTVSystem
spring.security.user.password=VoTaDuy


fileUpload.root_path=D:\pdfFiles